### PR TITLE
Izuma rebranding / refactoring

### PR DESCRIPTION
**Pull request by JanneKiiskila**
* Rebranding of Pelion to Izuma.
* Refactor the name of `pelion_systest_lib` to `izuma_systest_lib`.
* Small changes to `.gitignore`.

### CODE REVIEW

**Review by petedyerarm — CHANGES_REQUESTED** [review]
Some Pelion remaining in  https://github.com/PelionIoT/e2e-edge-test-suite/blob/Izuma/izuma_systest_lib/edge/remote_terminal.py

e.g. 
https://github.com/PelionIoT/e2e-edge-test-suite/blob/c62e89c8e89b04718a66e4dc15899ed8548ceb31/izuma_systest_lib/edge/remote_terminal.py#L31
https://github.com/PelionIoT/e2e-edge-test-suite/blob/c62e89c8e89b04718a66e4dc15899ed8548ceb31/izuma_systest_lib/edge/remote_terminal.py#L126

**Comment by JanneKiiskila** [comment]
That has now been fixed. Good spot, thanks!

**Review by petedyerarm — APPROVED** [review]
LGTM

**Review by petedyerarm — APPROVED** [review]
LGTM

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/edge-ci/pull/446 - this should fix the CI failures.

**Comment by JanneKiiskila** [comment]
CI passed on re-run.

**Pull request merged**
